"""File filtering & language detection — deterministic, no AI.

Decides which files are first-party source worth ingesting, and skips the
vendored / generated / dependency noise that dominates real repos.
"""

from __future__ import annotations

import os
from pathlib import Path

# Directories we never descend into.
IGNORE_DIRS = {
    ".git", ".hg", ".svn",
    "node_modules", "bower_components", "vendor",
    "venv", ".venv", "env", ".env", "virtualenv",
    "site-packages", ".tox", ".nox",
    "dist", "build", "out", "target", "bin", "obj",
    "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    ".idea", ".vscode", ".redcell",
    "migrations",  # usually autogenerated
}

# Extension -> language. Only languages we can parse are "active"; others are
# recorded/skipped so stats still reflect the whole repo.
LANG_BY_EXT = {
    ".py": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
}

# Languages the parser layer can currently handle end-to-end.
PARSEABLE = {"python"}


def detect_lang(path: Path) -> str | None:
    """Return the language for a file, or None if not a known source file."""
    return LANG_BY_EXT.get(path.suffix.lower())


def is_ignored_dir(name: str) -> bool:
    """True if a directory should be skipped (explicit list or hidden dir)."""
    return name in IGNORE_DIRS or (name.startswith(".") and name not in {".", ".."})


def iter_source_files(root: str | Path):
    """Yield Path objects for every known-language source file under root,
    skipping ignored directories. Deterministic order (sorted)."""
    root = Path(root)
    for dirpath, dirnames, filenames in os.walk(root):
        # Prune ignored dirs in place so os.walk won't descend into them.
        dirnames[:] = sorted(d for d in dirnames if not is_ignored_dir(d))
        for fname in sorted(filenames):
            p = Path(dirpath) / fname
            if detect_lang(p) is not None:
                yield p
